import Foundation

extension BuiltInThemes {
    /// Themes ported from `packages/web/packages/themes/src/styles/*.css` so the
    /// Swift and web catalogues match. These are brand themes with no ANSI
    /// palette of their own: `ansi` is derived from their semantic colours as a
    /// best-effort fill for the terminal feature, while `roleOverrides` carries
    /// the exact web values that drive chat and `typography` carries each
    /// theme's `--pc-font` / `--font-mono` stack.
    ///
    /// Generated by `scripts/generate_web_theme_swift.py` from
    /// `scripts/extract_web_themes.py`'s output — do not hand-edit; re-run the
    /// generator instead. See `docs/superpowers/plans/2026-08-30-swift-chat-parity.md`,
    /// Task 4.
    ///
    /// 21 of the manifest's 39 keys. The `adh*` font-variant family (8) is
    /// absent because those share one palette and differ only in typography, a
    /// web font-loading concern with no Swift analogue; the ten editor palettes
    /// (dracula, nord, gruvbox, solarized, catppuccin, github, monokai,
    /// one-dark, tokyo-night, rose-pine) are absent because Swift already
    /// ships them as terminal themes with real ANSI palettes — porting the web
    /// copies would give us two of each, and the web copy would be the worse
    /// one.
    public static let webPorted: [ColorTheme] = [
        charcoal,
        signal,
        terminal,
        terminalSplit,
        greenMatrix,
        greenMatrixGlass,
        oldSchoolTerminal,
        crtMonitor,
        handheldCommunicator,
        synthwave84,
        cobalt2,
        vesper,
        professional,
        techy,
        whimsical,
        fishlamp,
        devTeam,
        mikeFullerton,
        myProjects,
        projectsOverview,
        agenticCookbook
    ]

    /// "Charcoal" — ported from the web theme catalogue (`charcoal.css`).
    /// Typography is web's own stack: `Iosevka`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let charcoal = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000101",
        name: "Charcoal",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#0c0c0fff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#0c0c0fff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#e08a3cff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#6b8afdff")!,
            RGBAColor(hexString: "#8a8a9aff")!,
            RGBAColor(hexString: "#14141aff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#e08a3cff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#6b8afdff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#14141af0")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a1f")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#c4a35a40")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#d9bb74ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#ffffff0f")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#8a8a9aff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Iosevka", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "Iosevka", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "Iosevka", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "Iosevka", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "Iosevka", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Iosevka", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Signal" — ported from the web theme catalogue (`signal.css`).
    /// Typography is web's own stack: `Space Grotesk`, code in `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let signal = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000102",
        name: "Signal",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#ece8dfff")!,
        background: RGBAColor(hexString: "#0a0c11ff")!,
        cursor: RGBAColor(hexString: "#f6b73cff")!,
        selection: RGBAColor(hexString: "#f6b73c4d")!,
        ansi: [
            RGBAColor(hexString: "#0a0c11ff")!,
            RGBAColor(hexString: "#e07070ff")!,
            RGBAColor(hexString: "#7bbd6bff")!,
            RGBAColor(hexString: "#e8974aff")!,
            RGBAColor(hexString: "#f6b73cff")!,
            RGBAColor(hexString: "#f6b73cff")!,
            RGBAColor(hexString: "#6ba7e0ff")!,
            RGBAColor(hexString: "#b9bdc7ff")!,
            RGBAColor(hexString: "#12161fff")!,
            RGBAColor(hexString: "#e07070ff")!,
            RGBAColor(hexString: "#7bbd6bff")!,
            RGBAColor(hexString: "#e8974aff")!,
            RGBAColor(hexString: "#f6b73cff")!,
            RGBAColor(hexString: "#f6b73cff")!,
            RGBAColor(hexString: "#6ba7e0ff")!,
            RGBAColor(hexString: "#ece8dfff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0a0c11ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a3040ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#f6b73cff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#12161fff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#12161fff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#f6b73cff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#ece8dfff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#f6b73cff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#ffc85aff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0a0c11ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#ece8df52")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#191d28ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#868d99ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#ece8dfff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Space Grotesk", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Space Grotesk", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Space Grotesk", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Space Grotesk", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Space Grotesk", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Terminal" — ported from the web theme catalogue (`terminal.css`).
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `IBM Plex Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let terminal = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000103",
        name: "Terminal",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#b0b0b0ff")!,
        background: RGBAColor(hexString: "#0a0a0aff")!,
        cursor: RGBAColor(hexString: "#33ff33ff")!,
        selection: RGBAColor(hexString: "#33ff334d")!,
        ansi: [
            RGBAColor(hexString: "#0a0a0aff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#c7bd4bff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#66ddffff")!,
            RGBAColor(hexString: "#888888ff")!,
            RGBAColor(hexString: "#111111ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#c7bd4bff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#66ddffff")!,
            RGBAColor(hexString: "#b0b0b0ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0a0a0aff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#333333ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#33ff33ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#0a0a0aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#33ff33ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#b0b0b0ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#444444ff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#ffcc00ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#d0d0d0ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "IBM Plex Mono", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "IBM Plex Mono", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "IBM Plex Mono", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "IBM Plex Mono", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "IBM Plex Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "IBM Plex Mono", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Terminal Split" — ported from the web theme catalogue (`terminal-split.css`).
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `IBM Plex Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let terminalSplit = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000104",
        name: "Terminal Split",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#d0d0d0ff")!,
        background: RGBAColor(hexString: "#0a0a0aff")!,
        cursor: RGBAColor(hexString: "#ffcc00ff")!,
        selection: RGBAColor(hexString: "#ffcc004d")!,
        ansi: [
            RGBAColor(hexString: "#0a0a0aff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#c7bd4bff")!,
            RGBAColor(hexString: "#ffcc00ff")!,
            RGBAColor(hexString: "#ffcc00ff")!,
            RGBAColor(hexString: "#66ddffff")!,
            RGBAColor(hexString: "#999999ff")!,
            RGBAColor(hexString: "#111111ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#33ff33ff")!,
            RGBAColor(hexString: "#c7bd4bff")!,
            RGBAColor(hexString: "#ffcc00ff")!,
            RGBAColor(hexString: "#ffcc00ff")!,
            RGBAColor(hexString: "#66ddffff")!,
            RGBAColor(hexString: "#d0d0d0ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0a0a0aff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#333333ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#33ff33ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#0a0a0aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#33ff33ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#b0b0b0ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#444444ff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#ffcc00ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#d0d0d0ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "IBM Plex Mono", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "IBM Plex Mono", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "IBM Plex Mono", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "IBM Plex Mono", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "IBM Plex Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "IBM Plex Mono", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Green Matrix" — ported from the web theme catalogue (`green-matrix.css`).
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let greenMatrix = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000105",
        name: "Green Matrix",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#00ff41ff")!,
        background: RGBAColor(hexString: "#000000ff")!,
        cursor: RGBAColor(hexString: "#00ff41ff")!,
        selection: RGBAColor(hexString: "#00ff414d")!,
        ansi: [
            RGBAColor(hexString: "#000000ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff418f")!,
            RGBAColor(hexString: "#050805ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff41ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#050805ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#00ff4159")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#050805ff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#00ff4166")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#aaffaaff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#aaffaaff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "JetBrains Mono", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "JetBrains Mono", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "JetBrains Mono", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "JetBrains Mono", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "JetBrains Mono", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Green Matrix (Glass)" — ported from the web theme catalogue (`green-matrix-glass.css`).
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let greenMatrixGlass = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000106",
        name: "Green Matrix (Glass)",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#00ff41ff")!,
        background: RGBAColor(hexString: "#000000ff")!,
        cursor: RGBAColor(hexString: "#00ff41ff")!,
        selection: RGBAColor(hexString: "#00ff414d")!,
        ansi: [
            RGBAColor(hexString: "#000000ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff418f")!,
            RGBAColor(hexString: "#050805ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff41ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#00ff4159")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#050805cc")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#00ff4166")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#aaffaaff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#aaffaaff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "JetBrains Mono", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "JetBrains Mono", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "JetBrains Mono", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "JetBrains Mono", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "JetBrains Mono", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Old School Terminal" — ported from the web theme catalogue (`old-school-terminal.css`).
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `VT323`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 1.0667x: web sets `body { font-size: 16px }` against a catalogue baseline of 15px.
    static let oldSchoolTerminal = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000107",
        name: "Old School Terminal",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#00ff41ff")!,
        background: RGBAColor(hexString: "#000000ff")!,
        cursor: RGBAColor(hexString: "#00ff41ff")!,
        selection: RGBAColor(hexString: "#00ff414d")!,
        ansi: [
            RGBAColor(hexString: "#000000ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff418f")!,
            RGBAColor(hexString: "#050805ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#c4bd4fff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff41ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#00ff4159")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#050805cc")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#00ff4166")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#aaffaaff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#aaffaaff")!
        ],
        typography: ThemeTypography(sizeScale: 1.0667, styles: [
            TextRole.title.rawValue: FontStyle(family: "VT323", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "VT323", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "VT323", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "VT323", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "VT323", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "VT323", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "CRT Monitor" — ported from the web theme catalogue (`crt-monitor.css`).
    /// This theme's CSS has no `--color-warning` or `--color-link`: ansi[3]/[11]
    /// fall back to `--color-accent`, and ansi[5]/[13] use the accent shifted
    /// toward magenta instead of `--color-link`.
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `VT323`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 1.2667x: web sets `body { font-size: 19px }` against a catalogue baseline of 15px.
    static let crtMonitor = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000108",
        name: "CRT Monitor",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#00ff41ff")!,
        background: RGBAColor(hexString: "#00000000")!,
        cursor: RGBAColor(hexString: "#00ff41ff")!,
        selection: RGBAColor(hexString: "#00ff414d")!,
        ansi: [
            RGBAColor(hexString: "#00000000")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#005fffff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff4180")!,
            RGBAColor(hexString: "#050805ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#005fffff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff41ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#00ff4159")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#040c069e")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.thinkingDoneText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#00ff4166")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#aaffaaff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#aaffaaff")!
        ],
        typography: ThemeTypography(sizeScale: 1.2667, styles: [
            TextRole.title.rawValue: FontStyle(family: "VT323", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "VT323", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "VT323", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "VT323", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "VT323", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "VT323", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Handheld Communicator" — ported from the web theme catalogue (`handheld-communicator.css`).
    /// This theme's CSS has no `--color-warning` or `--color-link`: ansi[3]/[11]
    /// fall back to `--color-accent`, and ansi[5]/[13] use the accent shifted
    /// toward magenta instead of `--color-link`.
    /// Web's CSS declares no `--pc-persona-bg`, `--pc-user-bg`, so this theme draws no bubble at all
    /// (`.pc-bubble` styles nothing but its width). The fill is overridden
    /// fully transparent rather than left to derive, and `MessageBubbleView`
    /// reads that as a flat transcript line — no padding, no corner radius.
    /// Typography is web's own stack: `VT323`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 1.2667x: web sets `body { font-size: 19px }` against a catalogue baseline of 15px.
    static let handheldCommunicator = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000109",
        name: "Handheld Communicator",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#00ff41ff")!,
        background: RGBAColor(hexString: "#00000000")!,
        cursor: RGBAColor(hexString: "#00ff41ff")!,
        selection: RGBAColor(hexString: "#00ff414d")!,
        ansi: [
            RGBAColor(hexString: "#00000000")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#005fffff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff4180")!,
            RGBAColor(hexString: "#050805ff")!,
            RGBAColor(hexString: "#ff5555ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#00ff41ff")!,
            RGBAColor(hexString: "#005fffff")!,
            RGBAColor(hexString: "#aaffaaff")!,
            RGBAColor(hexString: "#00ff41ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#00ff4159")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#040c069e")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.thinkingDoneText.rawValue: RGBAColor(hexString: "#00ff41ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#00ff4166")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#aaffaaff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#aaffaaff")!
        ],
        typography: ThemeTypography(sizeScale: 1.2667, styles: [
            TextRole.title.rawValue: FontStyle(family: "VT323", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "VT323", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "VT323", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "VT323", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "VT323", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "VT323", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Synthwave '84" — ported from the web theme catalogue (`synthwave84.css`).
    /// Typography is web's own stack: `Exo 2`, code in `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let synthwave84 = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000110",
        name: "Synthwave '84",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#f2f0f5ff")!,
        background: RGBAColor(hexString: "#262335ff")!,
        cursor: RGBAColor(hexString: "#ff7edbff")!,
        selection: RGBAColor(hexString: "#ff7edb4d")!,
        ansi: [
            RGBAColor(hexString: "#262335ff")!,
            RGBAColor(hexString: "#fe4450ff")!,
            RGBAColor(hexString: "#72f1b8ff")!,
            RGBAColor(hexString: "#fede5dff")!,
            RGBAColor(hexString: "#ff7edbff")!,
            RGBAColor(hexString: "#ff7edbff")!,
            RGBAColor(hexString: "#03edf9ff")!,
            RGBAColor(hexString: "#c8c4ddff")!,
            RGBAColor(hexString: "#302c4aff")!,
            RGBAColor(hexString: "#fe4450ff")!,
            RGBAColor(hexString: "#72f1b8ff")!,
            RGBAColor(hexString: "#fede5dff")!,
            RGBAColor(hexString: "#ff7edbff")!,
            RGBAColor(hexString: "#ff7edbff")!,
            RGBAColor(hexString: "#03edf9ff")!,
            RGBAColor(hexString: "#f2f0f5ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#262335ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#494566ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#ff7edbff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#302c4aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#302c4aff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#ff7edbff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#f2f0f5ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#ff7edbff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#ff9de4ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#262335ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#f2f0f552")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#383455ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#9a94bdff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#f2f0f5ff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Exo 2", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Exo 2", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Exo 2", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Exo 2", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Exo 2", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Cobalt2" — ported from the web theme catalogue (`cobalt2.css`).
    /// Typography is web's own stack: `Rubik`, code in `Victor Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let cobalt2 = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000111",
        name: "Cobalt2",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#ffffffff")!,
        background: RGBAColor(hexString: "#193549ff")!,
        cursor: RGBAColor(hexString: "#ffc600ff")!,
        selection: RGBAColor(hexString: "#ffc6004d")!,
        ansi: [
            RGBAColor(hexString: "#193549ff")!,
            RGBAColor(hexString: "#ff628cff")!,
            RGBAColor(hexString: "#3ad900ff")!,
            RGBAColor(hexString: "#ff9d00ff")!,
            RGBAColor(hexString: "#ffc600ff")!,
            RGBAColor(hexString: "#ffc600ff")!,
            RGBAColor(hexString: "#0088ffff")!,
            RGBAColor(hexString: "#c5d4deff")!,
            RGBAColor(hexString: "#21425cff")!,
            RGBAColor(hexString: "#ff628cff")!,
            RGBAColor(hexString: "#3ad900ff")!,
            RGBAColor(hexString: "#ff9d00ff")!,
            RGBAColor(hexString: "#ffc600ff")!,
            RGBAColor(hexString: "#ffc600ff")!,
            RGBAColor(hexString: "#0088ffff")!,
            RGBAColor(hexString: "#ffffffff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#193549ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#35597aff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#ffc600ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#21425cff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#21425cff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#ffc600ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#ffffffff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#ffc600ff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#ffd747ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#193549ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#ffffff52")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#264b68ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#8fa8b8ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#ffffffff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Rubik", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Rubik", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Rubik", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Rubik", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "Victor Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Rubik", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Vesper" — ported from the web theme catalogue (`vesper.css`).
    /// Typography is web's own stack: `Geist`, code in `Geist Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let vesper = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000112",
        name: "Vesper",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#ffffffff")!,
        background: RGBAColor(hexString: "#101010ff")!,
        cursor: RGBAColor(hexString: "#ffc799ff")!,
        selection: RGBAColor(hexString: "#ffc7994d")!,
        ansi: [
            RGBAColor(hexString: "#101010ff")!,
            RGBAColor(hexString: "#ff8080ff")!,
            RGBAColor(hexString: "#99ffe4ff")!,
            RGBAColor(hexString: "#ffcf8fff")!,
            RGBAColor(hexString: "#ffc799ff")!,
            RGBAColor(hexString: "#ffc799ff")!,
            RGBAColor(hexString: "#a2d8cdff")!,
            RGBAColor(hexString: "#a0a0a0ff")!,
            RGBAColor(hexString: "#1c1c1cff")!,
            RGBAColor(hexString: "#ff8080ff")!,
            RGBAColor(hexString: "#99ffe4ff")!,
            RGBAColor(hexString: "#ffcf8fff")!,
            RGBAColor(hexString: "#ffc799ff")!,
            RGBAColor(hexString: "#ffc799ff")!,
            RGBAColor(hexString: "#a2d8cdff")!,
            RGBAColor(hexString: "#ffffffff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#101010ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#282828ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#ffc799ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#1c1c1cff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#1c1c1cff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#ffc799ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#ffffffff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#ffc799ff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#ffcfa8ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#101010ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#ffffff52")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#232323ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#a0a0a0ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#ffffffff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Geist", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Geist", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Geist", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Geist", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "Geist Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Geist", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Professional" — ported from the web theme catalogue (`professional.css`).
    /// Typography is web's own stack: `Inter`, code in `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let professional = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000113",
        name: "Professional",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8eaedff")!,
        background: RGBAColor(hexString: "#0e1620ff")!,
        cursor: RGBAColor(hexString: "#8aa8d4ff")!,
        selection: RGBAColor(hexString: "#8aa8d44d")!,
        ansi: [
            RGBAColor(hexString: "#0e1620ff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#8aa8d4ff")!,
            RGBAColor(hexString: "#8aa8d4ff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#a8b0bdff")!,
            RGBAColor(hexString: "#16202dff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#8aa8d4ff")!,
            RGBAColor(hexString: "#8aa8d4ff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#e8eaedff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0e1620ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a3848ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#8aa8d4ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#16202dff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#2a4a72ff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#ffffffb2")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#ffffffff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#8aa8d4ff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#a8c0e0ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0e1620ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#e8eaed4c")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#1e2a38ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#a8b0bdff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8eaedff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Inter", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Inter", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Inter", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Inter", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Inter", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Techy" — ported from the web theme catalogue (`techy.css`).
    /// Typography is web's own stack: `Inter`, code in `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let techy = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000114",
        name: "Techy",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#c9d1d9ff")!,
        background: RGBAColor(hexString: "#0d1117ff")!,
        cursor: RGBAColor(hexString: "#00ff88ff")!,
        selection: RGBAColor(hexString: "#00ff884d")!,
        ansi: [
            RGBAColor(hexString: "#0d1117ff")!,
            RGBAColor(hexString: "#f85149ff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#c1bb6aff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#00d4ffff")!,
            RGBAColor(hexString: "#8b949eff")!,
            RGBAColor(hexString: "#161b22ff")!,
            RGBAColor(hexString: "#f85149ff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#c1bb6aff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#00ff88ff")!,
            RGBAColor(hexString: "#00d4ffff")!,
            RGBAColor(hexString: "#c9d1d9ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0d1117ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#30363dff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#00ff88ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#161b22ff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#00ff8814")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#00ff884c")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#00ff88ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#c9d1d9ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#00ff88ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0d1117ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#484f58ff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#00d4ff14")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#00d4ff4c")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#00d4ffff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#c9d1d9ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "Inter", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Inter", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Inter", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Inter", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Inter", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Whimsical" — ported from the web theme catalogue (`whimsical.css`).
    /// Web defines `--pc-persona-bg`, `--pc-user-bg`, `--pc-send-bg` as `linear-gradient(...)`, not solid colours.
    /// `ColorTheme` holds solid `RGBAColor` values, so this theme renders a solid
    /// where web renders a gradient — the gradient's first colour stop, sampled
    /// deterministically:
    ///   - `--pc-persona-bg` -> `.personaBubble` = `#c8506aff`
    ///   - `--pc-user-bg` -> `.userBubble` = `#5a4a98ff`
    ///   - `--pc-send-bg` -> `.sendButton` = `#c8506aff`
    /// Typography is web's own stack: `Nunito`, code in `JetBrains Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 1.0667x: web sets `body { font-size: 16px }` against a catalogue baseline of 15px.
    static let whimsical = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000115",
        name: "Whimsical",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#f5e8f5ff")!,
        background: RGBAColor(hexString: "#1a1024ff")!,
        cursor: RGBAColor(hexString: "#f08aa8ff")!,
        selection: RGBAColor(hexString: "#f08aa84d")!,
        ansi: [
            RGBAColor(hexString: "#1a1024ff")!,
            RGBAColor(hexString: "#e87878ff")!,
            RGBAColor(hexString: "#7fc97aff")!,
            RGBAColor(hexString: "#bba879ff")!,
            RGBAColor(hexString: "#f08aa8ff")!,
            RGBAColor(hexString: "#f08aa8ff")!,
            RGBAColor(hexString: "#a8b0e0ff")!,
            RGBAColor(hexString: "#c0a8d8ff")!,
            RGBAColor(hexString: "#2a1a3aff")!,
            RGBAColor(hexString: "#e87878ff")!,
            RGBAColor(hexString: "#7fc97aff")!,
            RGBAColor(hexString: "#bba879ff")!,
            RGBAColor(hexString: "#f08aa8ff")!,
            RGBAColor(hexString: "#f08aa8ff")!,
            RGBAColor(hexString: "#a8b0e0ff")!,
            RGBAColor(hexString: "#f5e8f5ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#1a102480")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#4a3858ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#a878c8ff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#1a1024b2")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c8506aff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#f8c0d0ff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#ffffffff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#c8506aff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#ffffffff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#ffffff66")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#5a4a98ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#c8b0e0ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#ffffffff")!
        ],
        typography: ThemeTypography(sizeScale: 1.0667, styles: [
            TextRole.title.rawValue: FontStyle(family: "Nunito", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Nunito", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Nunito", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Nunito", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "JetBrains Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Nunito", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Fishlamp" — ported from the web theme catalogue (`fishlamp.css`).
    /// Typography is web's own stack: `Iosevka`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let fishlamp = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000116",
        name: "Fishlamp",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#f0e4d0ff")!,
        background: RGBAColor(hexString: "#0b0a09ff")!,
        cursor: RGBAColor(hexString: "#e8a33dff")!,
        selection: RGBAColor(hexString: "#e8a33d4d")!,
        ansi: [
            RGBAColor(hexString: "#0b0a09ff")!,
            RGBAColor(hexString: "#d9573bff")!,
            RGBAColor(hexString: "#8faa6bff")!,
            RGBAColor(hexString: "#ffd98aff")!,
            RGBAColor(hexString: "#e8a33dff")!,
            RGBAColor(hexString: "#e8a33dff")!,
            RGBAColor(hexString: "#8797b3ff")!,
            RGBAColor(hexString: "#a8968aff")!,
            RGBAColor(hexString: "#17130fff")!,
            RGBAColor(hexString: "#d9573bff")!,
            RGBAColor(hexString: "#8faa6bff")!,
            RGBAColor(hexString: "#ffd98aff")!,
            RGBAColor(hexString: "#e8a33dff")!,
            RGBAColor(hexString: "#e8a33dff")!,
            RGBAColor(hexString: "#8797b3ff")!,
            RGBAColor(hexString: "#f0e4d0ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0b0a09ff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#e8a33d2e")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#e8a33dff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#17130ff0")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#e8a33d24")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#e8a33d40")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#e8a33dff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#f0e4d0ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#e8a33dff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#f5c877ff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0b0a09ff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#7a6a5cff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#f0e4d00f")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#e8a33d2e")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#a8968aff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#f0e4d0ff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Iosevka", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "Iosevka", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "Iosevka", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "Iosevka", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "Iosevka", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Iosevka", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "Dev Team" — ported from the web theme catalogue (`dev-team.css`).
    /// Typography is web's own stack: `Manrope`, code in `DM Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let devTeam = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000117",
        name: "Dev Team",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#14141aff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#14141aff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#8b8b9bff")!,
            RGBAColor(hexString: "#1c1c24ff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#14141aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a14")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#5cb27014")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#5cb270ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "Manrope", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Manrope", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Manrope", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Manrope", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "DM Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Manrope", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Mike Fullerton" — ported from the web theme catalogue (`mikefullerton.css`).
    /// Typography is web's own stack: `DM Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9x: web sets `body { font-size: 13.5px }` against a catalogue baseline of 15px.
    static let mikeFullerton = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000118",
        name: "Mike Fullerton",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#0e0e14ff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#0e0e14ff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#8a8a9aff")!,
            RGBAColor(hexString: "#14141cb2")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0f99")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#0e0e148c")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a14")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#c4a35a26")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#5a8fd414")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#5a8fd426")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#5a8fd4ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9, styles: [
            TextRole.title.rawValue: FontStyle(family: "DM Mono", size: 22, weight: .semibold, monospaced: true),
            TextRole.heading.rawValue: FontStyle(family: "DM Mono", size: 15, weight: .semibold, monospaced: true),
            TextRole.body.rawValue: FontStyle(family: "DM Mono", size: 13, weight: .regular, monospaced: true),
            TextRole.caption.rawValue: FontStyle(family: "DM Mono", size: 11, weight: .regular, monospaced: true),
            TextRole.code.rawValue: FontStyle(family: "DM Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "DM Mono", size: 13, weight: .medium, monospaced: true)
        ])
    )

    /// "My Projects" — ported from the web theme catalogue (`myprojects.css`).
    /// Typography is web's own stack: `Manrope`, code in `DM Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.9333x: web sets `body { font-size: 14px }` against a catalogue baseline of 15px.
    static let myProjects = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000119",
        name: "My Projects",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#14141aff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#14141aff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#d4a754ff")!,
            RGBAColor(hexString: "#8b8b9bff")!,
            RGBAColor(hexString: "#1c1c24ff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#d4a754ff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#14141aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a14")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#d4b36aff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#d4a75414")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#d4a754ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.9333, styles: [
            TextRole.title.rawValue: FontStyle(family: "Manrope", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Manrope", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Manrope", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Manrope", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "DM Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Manrope", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Projects Overview" — ported from the web theme catalogue (`myprojectsoverview.css`).
    /// Typography is web's own stack: `Manrope`, code in `DM Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    /// Type is scaled 0.8667x: web sets `body { font-size: 13px }` against a catalogue baseline of 15px.
    static let projectsOverview = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000120",
        name: "Projects Overview",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#14141aff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#14141aff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#8b8b9bff")!,
            RGBAColor(hexString: "#1c1c24ff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#14141aff")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a0f")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#00000000")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#5a8fd40f")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#5a8fd4ff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(sizeScale: 0.8667, styles: [
            TextRole.title.rawValue: FontStyle(family: "Manrope", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Manrope", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Manrope", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Manrope", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "DM Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Manrope", size: 13, weight: .medium, monospaced: false)
        ])
    )

    /// "Agentic Cookbook" — ported from the web theme catalogue (`agenticcookbookweb.css`).
    /// Typography is web's own stack: `Manrope`, code in `DM Mono`, falling back to the
    /// system face at the same metrics when the family is not installed.
    static let agenticCookbook = ColorTheme(
        id: "B1B6F0E2-0000-4000-8000-000000000121",
        name: "Agentic Cookbook",
        appearance: .dark,
        isBuiltIn: true,
        attribution: "Agentic Developer Toolkit",
        foreground: RGBAColor(hexString: "#e8e6e3ff")!,
        background: RGBAColor(hexString: "#0c0c0fff")!,
        cursor: RGBAColor(hexString: "#c4a35aff")!,
        selection: RGBAColor(hexString: "#c4a35a4d")!,
        ansi: [
            RGBAColor(hexString: "#0c0c0fff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#8a8a9aff")!,
            RGBAColor(hexString: "#14141aff")!,
            RGBAColor(hexString: "#d45454ff")!,
            RGBAColor(hexString: "#5cb270ff")!,
            RGBAColor(hexString: "#a58e63ff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#c4a35aff")!,
            RGBAColor(hexString: "#5a8fd4ff")!,
            RGBAColor(hexString: "#e8e6e3ff")!
        ],
        roleOverrides: [
            ThemeRole.chatInputBackground.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.chatInputBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.chatInputFocus.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.chatSurface.rawValue: RGBAColor(hexString: "#14141af0")!,
            ThemeRole.personaBubble.rawValue: RGBAColor(hexString: "#c4a35a1f")!,
            ThemeRole.personaBubbleBorder.rawValue: RGBAColor(hexString: "#c4a35a40")!,
            ThemeRole.personaName.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.personaText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!,
            ThemeRole.sendButton.rawValue: RGBAColor(hexString: "#c4a35aff")!,
            ThemeRole.sendButtonHover.rawValue: RGBAColor(hexString: "#d4b36aff")!,
            ThemeRole.sendButtonText.rawValue: RGBAColor(hexString: "#0c0c0fff")!,
            ThemeRole.timestampText.rawValue: RGBAColor(hexString: "#5a5a6aff")!,
            ThemeRole.userBubble.rawValue: RGBAColor(hexString: "#ffffff0f")!,
            ThemeRole.userBubbleBorder.rawValue: RGBAColor(hexString: "#2a2a36ff")!,
            ThemeRole.userName.rawValue: RGBAColor(hexString: "#8a8a9aff")!,
            ThemeRole.userText.rawValue: RGBAColor(hexString: "#e8e6e3ff")!
        ],
        typography: ThemeTypography(styles: [
            TextRole.title.rawValue: FontStyle(family: "Manrope", size: 22, weight: .semibold, monospaced: false),
            TextRole.heading.rawValue: FontStyle(family: "Manrope", size: 15, weight: .semibold, monospaced: false),
            TextRole.body.rawValue: FontStyle(family: "Manrope", size: 13, weight: .regular, monospaced: false),
            TextRole.caption.rawValue: FontStyle(family: "Manrope", size: 11, weight: .regular, monospaced: false),
            TextRole.code.rawValue: FontStyle(family: "DM Mono", size: 12, weight: .regular, monospaced: true),
            TextRole.button.rawValue: FontStyle(family: "Manrope", size: 13, weight: .medium, monospaced: false)
        ])
    )
}
